"""
Django settings for global_banker project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from datetime import timedelta
from pathlib import Path
import os

# Load environment variables from .env file
# This MUST happen before any settings that depend on environment variables
# Try multiple paths to find .env file (handles different execution contexts)
env_paths = [
    Path(__file__).resolve().parent.parent / '.env',  # Standard location
    Path.cwd() / '.env',  # Current working directory
    Path(__file__).resolve().parent / '.env',  # Same dir as settings.py
]

env_path = None
for path in env_paths:
    if path.exists():
        env_path = path
        break

if env_path:
    try:
        from dotenv import load_dotenv
        # Always load .env file - use override=True to ensure .env values are used
        # This ensures the variable is loaded even if Django reloader creates new processes
        result = load_dotenv(dotenv_path=env_path, override=True)
        
        # Verify it was loaded
        xpub_loaded = os.environ.get('DEFAULT_XPUB', '')
        if not xpub_loaded:
            # Fallback: read directly from file if load_dotenv didn't work
            try:
                with open(env_path, 'r', encoding='utf-8') as f:
                    for line in f:
                        line = line.strip()
                        if not line or line.startswith('#'):
                            continue
                        if 'DEFAULT_XPUB' in line and '=' in line:
                            # Handle both DEFAULT_XPUB=value and DEFAULT_XPUB = value
                            if '=' in line:
                                key, value = line.split('=', 1)
                                key = key.strip()
                                if key == 'DEFAULT_XPUB':
                                    value = value.strip()
                                    # Remove quotes
                                    if value.startswith('"') and value.endswith('"'):
                                        value = value[1:-1]
                                    elif value.startswith("'") and value.endswith("'"):
                                        value = value[1:-1]
                                    if value:
                                        os.environ['DEFAULT_XPUB'] = value
                                        xpub_loaded = value
                                        break
            except Exception as e:
                print(f"⚠ Failed to read DEFAULT_XPUB from .env file: {e}")
        
        if xpub_loaded:
            print(f"✓ Loaded .env file from {env_path}")
            print(f"✓ DEFAULT_XPUB loaded (length: {len(xpub_loaded)})")
            # Ensure it's definitely in os.environ
            os.environ['DEFAULT_XPUB'] = xpub_loaded
        else:
            print(f"⚠ .env file exists at {env_path} but DEFAULT_XPUB not found")
            print(f"  File readable: {env_path.is_file()}")
    except ImportError:
        # Fallback: manually read .env file if python-dotenv is not installed
        print(f"⚠ python-dotenv not installed, manually loading .env from {env_path}")
        try:
            with open(env_path, 'r', encoding='utf-8') as f:
                for line in f:
                    line = line.strip()
                    # Skip comments and empty lines
                    if not line or line.startswith('#'):
                        continue
                    # Parse KEY=VALUE format
                    if '=' in line:
                        key, value = line.split('=', 1)
                        key = key.strip()
                        value = value.strip()
                        # Remove quotes if present
                        if value.startswith('"') and value.endswith('"'):
                            value = value[1:-1]
                        elif value.startswith("'") and value.endswith("'"):
                            value = value[1:-1]
                        # Set environment variable (override existing if needed)
                        if key and value:
                            os.environ[key] = value
            xpub_loaded = os.environ.get('DEFAULT_XPUB', '')
            print(f"✓ Manually loaded .env file")
            if xpub_loaded:
                print(f"✓ DEFAULT_XPUB found in .env (length: {len(xpub_loaded)})")
            else:
                print(f"⚠ DEFAULT_XPUB not found in .env file")
        except Exception as e:
            print(f"⚠ Failed to manually load .env file: {e}")
else:
    print(f"⚠ .env file not found in any of these locations: {env_paths}")

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-8xaiupqx2(dmj-0w58=#-mfyks!@&ml!%9=_iig#=yqp&cv6ac'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'django_filters',
    'corsheaders',
    'djmoney',
    'accounts',
    'catalog',
    'transactions',
    'orders',
    'wallet',
    'notifications',
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
}

# JWT Settings
# Access token expires after 15 minutes
# Refresh token also expires after 15 minutes to enforce inactivity timeout
# Users will be logged out after 15 minutes of no activity
# Note: Frontend automatically refreshes tokens on API calls, so active users stay logged in
# Sliding-session controls (minutes of inactivity before frontend will log user out)
SESSION_IDLE_TIMEOUT_MINUTES = int(os.getenv('SESSION_IDLE_TIMEOUT_MINUTES', '15'))

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=5),
    'REFRESH_TOKEN_LIFETIME': timedelta(hours=int(os.getenv('REFRESH_TOKEN_HOURS', '12'))),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'UPDATE_LAST_LOGIN': True,
}

# CORS Settings
CORS_ALLOWED_ORIGINS = [
    'http://localhost:5173',  # Vite dev server (default)
    'http://localhost:8080',  # Alternative Vite port
    'http://localhost:8081',  # Alternative Vite port
    'http://80.78.23.17',     # Production IP
    'http://80.78.23.17:8080', # Vite dev server on production IP
    'http://80.78.23.17:8081', # Vite dev server on production IP (alternative)
    'http://80.78.23.17:8082', # Vite dev server on production IP (alternative)
    'http://bvnkpro.com',     # Production domain
    'https://bvnkpro.com',    # Production domain (HTTPS)
    'http://www.bvnkpro.com', # Production domain
    'https://www.bvnkpro.com', # Production domain (HTTPS)
]

CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# Wallet Settings
# Extended public key (xpub) for address derivation
# WARNING: Never store xprv (extended private key) on the server
# In production, encrypt this value and store in secret manager
# NOTE: This is loaded AFTER .env file is loaded above, so it will pick up DEFAULT_XPUB from .env
DEFAULT_XPUB = os.getenv('DEFAULT_XPUB', '')  # Set via environment variable in production

# Test mode: Use mock addresses instead of real blockchain
# Set to False in production when using real blockchain
WALLET_TEST_MODE = os.getenv('WALLET_TEST_MODE', 'False').lower() == 'true'

# Verify DEFAULT_XPUB was loaded (for debugging)
if DEFAULT_XPUB:
    print(f"✓ DEFAULT_XPUB loaded (length: {len(DEFAULT_XPUB)})")
else:
    print("⚠ DEFAULT_XPUB not set - wallet address derivation will fail")

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    # CSRF disabled - using JWT authentication which doesn't need CSRF protection
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'global_banker.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'global_banker.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Cache configuration (for exchange rates)
# Using Redis for better performance and shared cache across processes
# Falls back to local memory cache if Redis is not available
REDIS_URL = os.getenv('REDIS_URL', 'redis://127.0.0.1:6379/1')
USE_REDIS = os.getenv('USE_REDIS', 'True').lower() == 'true'

if USE_REDIS:
    # Use Redis cache backend (Django will handle connection errors gracefully)
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.redis.RedisCache',
            'LOCATION': REDIS_URL,
            'KEY_PREFIX': 'global_banker',
            'TIMEOUT': 10,  # 10 seconds default (for exchange rates)
        }
    }
else:
    # Use local memory cache (works without Redis)
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'unique-snowflake',
            'TIMEOUT': 10,  # 10 seconds default (for exchange rates)
        }
    }

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Email Configuration
EMAIL_BACKEND = os.getenv('EMAIL_BACKEND', 'django.core.mail.backends.console.EmailBackend')
EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', '587'))
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True').lower() == 'true'
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'noreply@example.com')
