# Generated by Django 5.2.7 on 2025-11-14 20:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('direction', models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit')], max_length=10)),
                ('category', models.CharField(choices=[('topup', 'Top Up'), ('purchase', 'Purchase'), ('transfer', 'Transfer'), ('fee', 'Fee'), ('refund', 'Refund'), ('adjustment', 'Adjustment')], max_length=20)),
                ('amount_minor', models.BigIntegerField()),
                ('currency_code', models.CharField(max_length=3)),
                ('description', models.CharField(max_length=500)),
                ('balance_after_minor', models.BigIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('related_order_id', models.UUIDField(blank=True, null=True)),
                ('related_topup_intent_id', models.UUIDField(blank=True, null=True)),
                ('related_onchain_tx_id', models.UUIDField(blank=True, null=True)),
                ('idempotency_key', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='transaction_user_id_f5864b_idx'), models.Index(fields=['user', 'category'], name='transaction_user_id_a385c1_idx'), models.Index(fields=['user', 'direction'], name='transaction_user_id_345150_idx'), models.Index(fields=['user', 'status'], name='transaction_user_id_9cef77_idx')],
            },
        ),
    ]
