# Generated by Django 5.2.7 on 2025-11-18 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='consolidation_tx_hash',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='sweep_tx_hash',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
