# Generated by Django 5.2.7 on 2025-11-14 22:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AddressIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='default', max_length=64, unique=True)),
                ('next_index', models.BigIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Address Indices',
            },
        ),
        migrations.CreateModel(
            name='CryptoNetwork',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('chain_id', models.CharField(blank=True, max_length=50)),
                ('explorer_url', models.URLField()),
                ('explorer_api_url', models.URLField()),
                ('decimals', models.IntegerField()),
                ('native_symbol', models.CharField(max_length=10)),
                ('derivation_path', models.CharField(default="m/84'/0'/0'", max_length=50)),
                ('xpub', models.TextField(blank=True)),
                ('is_testnet', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('required_confirmations', models.IntegerField(default=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DepositAddress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=128, unique=True)),
                ('index', models.BigIntegerField()),
                ('memo_tag', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposit_addresses', to='wallet.cryptonetwork')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposit_addresses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TopUpIntent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount_minor', models.BigIntegerField()),
                ('currency_code', models.CharField(default='USD', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('awaiting_confirmations', 'Awaiting Confirmations'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('expired', 'Expired')], default='pending', max_length=30)),
                ('provider_ref', models.CharField(blank=True, max_length=200)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deposit_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topup_intents', to='wallet.depositaddress')),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topup_intents', to='wallet.cryptonetwork')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topup_intents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OnChainTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tx_hash', models.CharField(max_length=128, unique=True)),
                ('from_address', models.CharField(max_length=128)),
                ('to_address', models.CharField(max_length=128)),
                ('amount_atomic', models.BigIntegerField()),
                ('amount_minor', models.BigIntegerField()),
                ('confirmations', models.IntegerField(default=0)),
                ('required_confirmations', models.IntegerField(default=2)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('occurred_at', models.DateTimeField()),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onchain_transactions', to='wallet.cryptonetwork')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onchain_transactions', to=settings.AUTH_USER_MODEL)),
                ('topup_intent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onchain_transactions', to='wallet.topupintent')),
            ],
            options={
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('currency_code', models.CharField(default='USD', max_length=3)),
                ('balance_minor', models.BigIntegerField(default=0)),
                ('pending_minor', models.BigIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='depositaddress',
            index=models.Index(fields=['user', 'network', 'is_active'], name='wallet_depo_user_id_ab2ee6_idx'),
        ),
        migrations.AddIndex(
            model_name='depositaddress',
            index=models.Index(fields=['address'], name='wallet_depo_address_3ac6c8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='depositaddress',
            unique_together={('user', 'network', 'index')},
        ),
        migrations.AddIndex(
            model_name='topupintent',
            index=models.Index(fields=['user', 'status'], name='wallet_topu_user_id_3c515e_idx'),
        ),
        migrations.AddIndex(
            model_name='topupintent',
            index=models.Index(fields=['user', 'created_at'], name='wallet_topu_user_id_0e48f6_idx'),
        ),
        migrations.AddIndex(
            model_name='topupintent',
            index=models.Index(fields=['status', 'expires_at'], name='wallet_topu_status_400e09_idx'),
        ),
        migrations.AddIndex(
            model_name='onchaintransaction',
            index=models.Index(fields=['user', 'status'], name='wallet_onch_user_id_cabccb_idx'),
        ),
        migrations.AddIndex(
            model_name='onchaintransaction',
            index=models.Index(fields=['tx_hash'], name='wallet_onch_tx_hash_7807cf_idx'),
        ),
        migrations.AddIndex(
            model_name='onchaintransaction',
            index=models.Index(fields=['topup_intent'], name='wallet_onch_topup_i_590502_idx'),
        ),
        migrations.AddIndex(
            model_name='onchaintransaction',
            index=models.Index(fields=['network', 'status'], name='wallet_onch_network_0290d6_idx'),
        ),
        migrations.AddIndex(
            model_name='wallet',
            index=models.Index(fields=['user', 'currency_code'], name='wallet_wall_user_id_38943c_idx'),
        ),
    ]
