# Generated by Django 5.2.7 on 2025-11-18 21:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ColdWallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=128, unique=True)),
                ('name', models.CharField(default='Main Reserve', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cold_wallets', to='wallet.cryptonetwork')),
            ],
            options={
                'ordering': ['network', 'name'],
            },
        ),
        migrations.CreateModel(
            name='HotWallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=128, unique=True)),
                ('encrypted_xprv', models.TextField()),
                ('derivation_path', models.CharField(max_length=100)),
                ('balance_atomic', models.BigIntegerField(default=0)),
                ('last_sweep_at', models.DateTimeField(blank=True, null=True)),
                ('last_consolidation_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hot_wallets', to='wallet.cryptonetwork')),
            ],
            options={
                'ordering': ['network', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConsolidationTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_address', models.CharField(max_length=128)),
                ('to_address', models.CharField(max_length=128)),
                ('amount_atomic', models.BigIntegerField()),
                ('tx_hash', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('fee_atomic', models.BigIntegerField(default=0)),
                ('confirmations', models.IntegerField(default=0)),
                ('required_confirmations', models.IntegerField(default=2)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('broadcast', 'Broadcast'), ('confirmed', 'Confirmed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('max_retries', models.IntegerField(default=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cold_wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consolidation_transactions', to='wallet.coldwallet')),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consolidation_transactions', to='wallet.cryptonetwork')),
                ('hot_wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consolidation_transactions', to='wallet.hotwallet')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SweepTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_address', models.CharField(max_length=128)),
                ('to_address', models.CharField(max_length=128)),
                ('amount_atomic', models.BigIntegerField()),
                ('tx_hash', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('fee_atomic', models.BigIntegerField(default=0)),
                ('confirmations', models.IntegerField(default=0)),
                ('required_confirmations', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('broadcast', 'Broadcast'), ('confirmed', 'Confirmed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('max_retries', models.IntegerField(default=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hot_wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sweep_transactions', to='wallet.hotwallet')),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sweep_transactions', to='wallet.cryptonetwork')),
                ('onchain_tx', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sweep_transaction', to='wallet.onchaintransaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sweep_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='coldwallet',
            index=models.Index(fields=['network', 'is_active'], name='wallet_cold_network_e58465_idx'),
        ),
        migrations.AddIndex(
            model_name='coldwallet',
            index=models.Index(fields=['address'], name='wallet_cold_address_75471b_idx'),
        ),
        migrations.AddIndex(
            model_name='hotwallet',
            index=models.Index(fields=['network', 'is_active'], name='wallet_hotw_network_510218_idx'),
        ),
        migrations.AddIndex(
            model_name='hotwallet',
            index=models.Index(fields=['address'], name='wallet_hotw_address_e27b30_idx'),
        ),
        migrations.AddIndex(
            model_name='consolidationtransaction',
            index=models.Index(fields=['status', 'created_at'], name='wallet_cons_status_192298_idx'),
        ),
        migrations.AddIndex(
            model_name='consolidationtransaction',
            index=models.Index(fields=['tx_hash'], name='wallet_cons_tx_hash_99c39e_idx'),
        ),
        migrations.AddIndex(
            model_name='consolidationtransaction',
            index=models.Index(fields=['network', 'status'], name='wallet_cons_network_61d5fb_idx'),
        ),
        migrations.AddIndex(
            model_name='consolidationtransaction',
            index=models.Index(fields=['hot_wallet', 'status'], name='wallet_cons_hot_wal_e27198_idx'),
        ),
        migrations.AddIndex(
            model_name='sweeptransaction',
            index=models.Index(fields=['status', 'created_at'], name='wallet_swee_status_0512e0_idx'),
        ),
        migrations.AddIndex(
            model_name='sweeptransaction',
            index=models.Index(fields=['tx_hash'], name='wallet_swee_tx_hash_20ddba_idx'),
        ),
        migrations.AddIndex(
            model_name='sweeptransaction',
            index=models.Index(fields=['onchain_tx'], name='wallet_swee_onchain_d4c4fc_idx'),
        ),
        migrations.AddIndex(
            model_name='sweeptransaction',
            index=models.Index(fields=['network', 'status'], name='wallet_swee_network_229e3a_idx'),
        ),
        migrations.AddIndex(
            model_name='sweeptransaction',
            index=models.Index(fields=['user', 'status'], name='wallet_swee_user_id_7560f5_idx'),
        ),
    ]
