# Generated by Django 5.2.7 on 2025-11-18 22:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_add_hot_cold_wallet_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='topupintent',
            name='wallet_topu_status_400e09_idx',
        ),
        migrations.RemoveField(
            model_name='topupintent',
            name='expires_at',
        ),
        migrations.RemoveField(
            model_name='topupintent',
            name='provider_ref',
        ),
        migrations.AlterField(
            model_name='topupintent',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='pending', max_length=30),
        ),
        migrations.AddIndex(
            model_name='topupintent',
            index=models.Index(fields=['status', 'created_at'], name='wallet_topu_status_e45942_idx'),
        ),
    ]
