# Generated by Django 5.2.7 on 2025-11-19 20:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_remove_topup_expiration_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OxaPayPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('track_id', models.CharField(max_length=100, unique=True)),
                ('address', models.CharField(max_length=128)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=20)),
                ('pay_amount', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('pay_currency', models.CharField(default='btc', max_length=10)),
                ('currency', models.CharField(default='usd', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('expired', 'Expired'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('callback_url', models.URLField(blank=True)),
                ('order_id', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('description', models.TextField(blank=True)),
                ('expired_at', models.DateTimeField(blank=True, null=True)),
                ('qr_code', models.URLField(blank=True)),
                ('raw_response', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oxapay_payments', to='wallet.cryptonetwork')),
                ('topup_intent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='oxapay_payments', to='wallet.topupintent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oxapay_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='wallet_oxap_user_id_533d1a_idx'), models.Index(fields=['track_id'], name='wallet_oxap_track_i_cfb905_idx'), models.Index(fields=['status', 'created_at'], name='wallet_oxap_status_e16139_idx'), models.Index(fields=['network', 'status'], name='wallet_oxap_network_3b50af_idx')],
            },
        ),
        migrations.CreateModel(
            name='OxaPayStaticAddress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('track_id', models.CharField(max_length=100, unique=True)),
                ('address', models.CharField(max_length=128, unique=True)),
                ('callback_url', models.URLField(blank=True)),
                ('order_id', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('description', models.TextField(blank=True)),
                ('qr_code', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('raw_response', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oxapay_static_addresses', to='wallet.cryptonetwork')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oxapay_static_addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'network', 'is_active'], name='wallet_oxap_user_id_74abfc_idx'), models.Index(fields=['track_id'], name='wallet_oxap_track_i_a75c9c_idx'), models.Index(fields=['address'], name='wallet_oxap_address_949d53_idx')],
            },
        ),
    ]
