# Generated by Django 5.2.7 on 2025-11-19 23:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_add_oxapay_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topupintent',
            name='deposit_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topup_intents', to='wallet.depositaddress'),
        ),
    ]
