# Generated by Django 5.2.7 on 2025-11-14 19:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('code', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('currency_code', models.CharField(max_length=3)),
                ('flag_url', models.URLField(blank=True)),
                ('is_supported', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Countries',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('logo_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banks', to='catalog.country')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sku', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('balance_minor', models.BigIntegerField()),
                ('price_minor', models.BigIntegerField()),
                ('currency_code', models.CharField(max_length=3)),
                ('image_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='catalog.bank')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='catalog.country')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='bank',
            index=models.Index(fields=['country', 'is_active'], name='catalog_ban_country_0b3d97_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['bank', 'country'], name='catalog_acc_bank_id_98a9ab_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['country', 'is_active'], name='catalog_acc_country_a3f19d_idx'),
        ),
    ]
