# Generated by Django 5.2.7 on 2025-11-14 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='account',
            name='catalog_acc_bank_id_98a9ab_idx',
        ),
        migrations.RemoveIndex(
            model_name='account',
            name='catalog_acc_country_a3f19d_idx',
        ),
        migrations.RemoveField(
            model_name='account',
            name='country',
        ),
        migrations.RemoveField(
            model_name='account',
            name='currency_code',
        ),
        migrations.AlterField(
            model_name='account',
            name='sku',
            field=models.CharField(editable=False, max_length=100, unique=True),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['bank', 'is_active'], name='catalog_acc_bank_id_b7e9ab_idx'),
        ),
    ]
