# Generated by Django 5.2.7 on 2025-11-14 20:08

import re
from django.db import migrations


def generate_sku(bank_name: str, account_id: str) -> str:
    """Generate SKU from bank name and UUID"""
    # Clean bank name: remove special chars, spaces -> uppercase, limit to 10 chars
    clean_name = re.sub(r'[^A-Za-z0-9]', '', bank_name.upper())[:10]
    # Get first 8 chars of UUID (without hyphens)
    uuid_part = account_id.replace('-', '')[:8].upper()
    return f"{clean_name}-{uuid_part}"


def generate_skus_for_existing_accounts(apps, schema_editor):
    """Generate SKUs for existing Account records"""
    Account = apps.get_model('catalog', 'Account')
    Bank = apps.get_model('catalog', 'Bank')
    
    for account in Account.objects.all():
        if not account.sku:
            bank = Bank.objects.get(id=account.bank_id)
            account.sku = generate_sku(bank.name, str(account.id))
            account.save(update_fields=['sku'])


def reverse_generate_skus(apps, schema_editor):
    """Reverse migration - clear SKUs (not really needed but required)"""
    Account = apps.get_model('catalog', 'Account')
    Account.objects.all().update(sku='')


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_remove_account_catalog_acc_bank_id_98a9ab_idx_and_more'),
    ]

    operations = [
        migrations.RunPython(generate_skus_for_existing_accounts, reverse_generate_skus),
    ]
