# Generated by Django 5.2.7 on 2025-11-20 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_fullz_fullzpackage'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='has_fullz',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bank',
            name='logs',
            field=models.TextField(blank=True, null=True),
        ),
    ]
