# Generated by Django 5.2.7 on 2025-11-21 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_add_has_fullz_to_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='has_fullz',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='bank',
            index=models.Index(fields=['has_fullz', 'is_active'], name='catalog_ban_has_ful_74ea72_idx'),
        ),
    ]
