# Generated by Django 5.2.7 on 2025-11-26 02:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_add_has_fullz_to_bank'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'account')},
        ),
        migrations.AddField(
            model_name='cartitem',
            name='fullz_package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='catalog.fullzpackage'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='fullz_package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='catalog.fullzpackage'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='catalog.account'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='catalog.account'),
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'account'), ('cart', 'fullz_package')},
        ),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('account__isnull', False), ('fullz_package__isnull', True)), models.Q(('account__isnull', True), ('fullz_package__isnull', False)), _connector='OR'), name='cart_item_must_have_account_or_package'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('account__isnull', False), ('fullz_package__isnull', True)), models.Q(('account__isnull', True), ('fullz_package__isnull', False)), _connector='OR'), name='order_item_must_have_account_or_package'),
        ),
    ]
