# Generated by Django 5.2.7 on 2025-12-02 20:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0002_alter_cartitem_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email_type', models.CharField(choices=[('order_confirmation', 'Order Confirmation'), ('payment_confirmation', 'Payment Confirmation'), ('order_cancellation', 'Order Cancellation'), ('order_delivery', 'Order Delivery')], max_length=50)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed'), ('bounced', 'Bounced')], default='sent', max_length=20)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_notifications', to='orders.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-sent_at'],
                'indexes': [models.Index(fields=['user', 'sent_at'], name='notificatio_user_id_01a825_idx'), models.Index(fields=['order', 'email_type'], name='notificatio_order_i_579556_idx')],
            },
        ),
    ]
