# Generated by Django 5.2.7 on 2026-01-07 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailnotification',
            name='email_type',
            field=models.CharField(choices=[('welcome', 'Welcome Email'), ('order_confirmation', 'Order Confirmation'), ('payment_confirmation', 'Payment Confirmation'), ('deposit_confirmation', 'Deposit Confirmation'), ('order_cancellation', 'Order Cancellation'), ('order_delivery', 'Order Delivery')], max_length=50),
        ),
    ]
